# Generated by Django 6.0.4 on 2026-04-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('volunteer', 'volunteeer'), ('institution', 'institution')], max_length=11),
        ),
    ]
